### ISSUE TITLE
Will be good to cache results on server

### ISSUE THREAD

**Issue by kutsy** [erikaheidi/placephant#14]
Hello.
Cool idea!
But will be good to cache results of image modification in file on server for faster response.

**Comment by henrikbjorn** [comment]
It is cached with httpcache.

**Comment by kutsy** [comment]
I mean about cache on disk.

**Comment by henrikbjorn** [comment]
They are, the http cache will cache the images for a specific period of time and return that. You can see them in app/cache folder and read more at http://symfony.com/doc/current/book/http_cache.html

I know you mean a generating cache, but the above are doing the same thing just in a more abstract way.

**Comment by kutsy** [comment]
OK. Its cool.
