### ISSUE TITLE
Use of Imagine lib

### ISSUE THREAD

**Issue by anthonysterling** [erikaheidi/placephant#3]
Hi.

Would you consider the use of the [Imagine](https://github.com/avalanche123/Imagine) library?

It already supports the image [filters/effects](http://imagine.readthedocs.org/en/latest/usage/effects.html#effects-api) you mention in the README, only requires PHP 5.3+, can use GD2/Gmagick/Imagick, and has a pretty nice API.

I'm happy to integrate if so.

**Comment by anthonysterling** [comment]
I see I may have made a bit of a social faux pas, given you're the author of imanee.

>.<

**Comment by erikaheidi** [comment]
No worries =) I know that Imagine is a good image library, but I would like to use Imanee because its still in development and this gives me an incentive to improve it. It has a simpler model, and I have some cool things planned for it.
